<?php
/*
	WARNING! DO NOT EDIT THIS FILE!
	This file is part of the core Bizznis parent theme. 
	Please do all modifications in the form of a child theme.
*/

/**
 * Handles display of 404 page.
 *
 * @since 1.0.0
 */
remove_action( 'bizznis_loop', 'bizznis_do_loop' ); #remove default loop
add_action( 'bizznis_loop', 'bizznis_404' ); #output a 404 "Not Found" error message
function bizznis_404() {
	?>
	<article class="entry">
		<h1 class="entry-title"><?php _e( 'Not found, error 404', 'bizznis' ); ?></h1>
		<div class="entry-content">
			<p><?php printf( __( 'The page you are looking for no longer exists. Perhaps you can return back to the site\'s <a href="%s">homepage</a> and see if you can find what you are looking for. Or, you can try finding it by using the search form below.', 'bizznis' ), home_url() ); ?></p>
			<p><?php get_search_form(); ?></p>
		</div>
	</article>
	<?php
}

bizznis(); #Fire the engine
