<?php
/*
	WARNING! DO NOT EDIT THIS FILE!
	This file is part of the core Bizznis parent theme. 
	Please do all modifications in the form of a child theme.
*/

//* Stop here if comments.php file doesn't exist
if ( ! empty( $_SERVER['SCRIPT_FILENAME'] ) && 'comments.php' === basename( $_SERVER['SCRIPT_FILENAME'] ) )
	die ( 'Please do not load this page directly. Thanks!' );

//* Stop here if the current post is protected by a password
if ( post_password_required() ) {
	printf( '<p class="alert">%s</p>', __( 'This post is password protected. Enter the password to view comments.', 'bizznis' ) );
	return;
}

//* Output semantically correct header if accessibility is supported
if ( bizznis_a11y( 'headings' ) ) {
	printf( '<h2 class="screen-reader-text">%s</h2>', __( 'Reader Interactions', 'bizznis' ) );
}

//* This hook handles all comments code
do_action( 'bizznis_comments' );
