<?php
/*
	WARNING! DO NOT EDIT THIS FILE!
	This file is part of the core Bizznis parent theme. 
	Please do all modifications in the form of a child theme.
*/

//* Stop here if the current post is protected by a password
if ( post_password_required() )
	return;

//* This hook handles all comments code
do_action( 'bizznis_comments' );
