<?php
/*
	WARNING! DO NOT EDIT THIS FILE!
	This file is part of the core Bizznis parent theme. 
	Please do all modifications in the form of a child theme.
*/

//* Handles the footer structure.
echo '</div>'; #end .site-container
do_action( 'bizznis_after_main_container' );
echo '</div>'; #end .site-main
do_action( 'bizznis_footer' );
echo '</div>'; #end .site-container
do_action( 'bizznis_after' );
wp_footer();
?>
</body>
</html>