<?php
/*
	WARNING! DO NOT EDIT THIS FILE!
	This file is part of the core Bizznis parent theme. 
	Please do all modifications in the form of a child theme.
*/

//* Handles the header structure.
?>
<!DOCTYPE html>
<html <?php language_attributes( 'html' ); ?>>
<head>
<meta charset="<?php bloginfo( 'charset' ); ?>" />
<?php wp_head(); ?>
</head>
<?php
printf( '<body %s>', bizznis_attr( 'body', array( 'class' => implode( ' ', get_body_class() ) ) ) );
do_action( 'bizznis_before' );
printf( '<div %s>', bizznis_attr( 'site-container' ) );
do_action( 'bizznis_header' );
printf( '<div %s>', bizznis_attr( 'site-main' ) );
do_action( 'bizznis_before_main_container' );
bizznis_wrapper( 'main-wrapper', 'open' ); #wrapper