<?php
/*
	WARNING! DO NOT EDIT THIS FILE!
	This file is part of the core Bizznis parent theme. 
	Please do all modifications in the form of a child theme.
*/

add_action( 'bizznis_site_title', 'bizznis_jetpack_logo', 9 );
/**
 * Echo the jetpack logo into the header.
 *
 * @since 1.0.0
 */
if ( ! function_exists( 'bizznis_jetpack_logo' ) ) :
function bizznis_jetpack_logo() {
	if ( function_exists( 'jetpack_the_site_logo' ) ) {
		jetpack_the_site_logo();
	}
}
endif;

add_action( 'customize_register', 'bizznis_jetpack_customizer', 20 );
/**
 * Modify customizer controls
 *
 * @since 1.0.0
 */
if ( ! function_exists( 'bizznis_jetpack_customizer' ) ) :
function bizznis_jetpack_customizer( $wp_customize ) {
	// Remove logo or title/tagline selection
	if ( function_exists( 'jetpack_the_site_logo' ) && current_theme_supports( 'site-logo' ) ) {
		$wp_customize->remove_control( 'bizznis_blog_title' );
		$wp_customize->remove_control( 'header_info' );
	}
}
endif;

add_filter( 'bizznis_pre_get_option_blog_title', 'jetpack_blog_title' );
/**
 * Override existing blog_title settings
 *
 * @since 1.0.0
 */
if ( ! function_exists( 'jetpack_blog_title' ) ) :
function jetpack_blog_title( $option ) {
	if ( function_exists( 'jetpack_the_site_logo' ) && current_theme_supports( 'site-logo' ) ) {
		return 'text';
	}
	return $option;
}
endif;