<?php
/*
	WARNING! DO NOT EDIT THIS FILE!
	This file is part of the core Bizznis parent theme. 
	Please do all modifications in the form of a child theme.
*/

//* Include widget class files
load_template( BIZZNIS_WIDGETS_DIR . '/featured-page-widget.php' );

/**
 * Register widgets for use in the Bizznis theme.
 *
 * @since 1.0.0
 */
add_action( 'widgets_init', 'bizznis_load_widgets' );
function bizznis_load_widgets() {
	register_widget( 'Bizznis_Featured_Page' );
}
