<?php
/*
	WARNING! DO NOT EDIT THIS FILE!
	This file is part of the core Bizznis parent theme. 
	Please do all modifications in the form of a child theme.
*/

/**
 * This file controls the top-level Bizznis menu.
 *
 * @since 1.0.0
 */
add_action( 'after_setup_theme', 'bizznis_add_admin_menu' );
function bizznis_add_admin_menu() {
	# Stop here, if not viewing the admin
	if ( ! is_admin() ) {
		return;
	}
	# Global variable
	global $_bizznis_admin_settings;
	# Don't add menu item if programatically disabled
	if ( ! current_theme_supports( 'bizznis-admin-menu' ) ) {
		return;
	}
	# Current user object
	$user = wp_get_current_user();
	# Don't add menu item if disabled for current user
	if ( ! get_the_author_meta( 'bizznis_admin_menu', $user->ID ) ) {
		return;
	}
	# Add "Settings" submenu item
	new Bizznis_Admin_Settings;
	# Hook here to create submenus
	do_action( 'bizznis_admin_menu' );

}

/**
 * Add submenu items under Bizznis in admin menu.
 *
 * @since 0.2.0
 */
add_action( 'bizznis_admin_menu', 'bizznis_add_admin_submenus' );
function bizznis_add_admin_submenus() {
	# Stop here, if not viewing the admin
	if ( ! is_admin() ) {
		return;
	}
	# Global variable
	global $_bizznis_admin_tools, $_bizznis_admin_readme;
	# Don't add submenu items if Bizznis menu is disabled
	if( ! current_theme_supports( 'bizznis-admin-menu' ) ) {
		return;
	}
	# Get current user
	$user = wp_get_current_user();
	# Add "Import/Export Settings" submenu item
	if ( current_theme_supports( 'bizznis-tools-settings-menu' ) && get_the_author_meta( 'bizznis_tools_settings_menu', $user->ID ) ) {
		$_bizznis_admin_tools = new Bizznis_Admin_Import_Export;
	}
}

/**
 * Add the feedback link to admin navigation
 *
 * @since 1.0.0
 */
add_action( 'bizznis_admin_title_right', 'bizznis_add_admin_menu_feedback', 15 );
function bizznis_add_admin_menu_feedback() {
	printf( __( '<a href="%s" target="_blank" class="feedback" title="Report a Bug">Report a Bug</a>', 'bizznis' ), esc_url( 'https://github.com/bizzthemes/bizznis/issues' ) );
}