<?php
/*
	WARNING! DO NOT EDIT THIS FILE!
	This file is part of the core Bizznis parent theme. 
	Please do all modifications in the form of a child theme.
*/

/**
 * Register a new admin page, providing content and corresponding menu item for the CPT Archive Settings page.
 *
 * @since 1.0.0
 */
class Bizznis_Admin_CPT_Archive_Settings extends Bizznis_Admin_Boxes {

	# Post type object.
	protected $post_type;

	/**
	 * Create an archive settings admin menu item and settings page for relevant custom post types.
	 *
	 * @since 1.0.0
	 */
	public function __construct( stdClass $post_type ) {
		$this->post_type = $post_type;
		$page_id = 'bizznis-cpt-archive-' . $this->post_type->name;
		$menu_ops = array(
			'submenu' => array (
				'parent_slug' => 'edit.php?post_type=' . $this->post_type->name,
				'page_title'  => apply_filters( 'bizznis_cpt_archive_settings_page_label', __( 'Archive Settings', 'bizznis' ) ),
				'menu_title'  => apply_filters( 'bizznis_cpt_archive_settings_menu_label', __( 'Archive Settings', 'bizznis' ) ),
				'capability'  => 'edit_theme_options',
			)
		);
		# Handle non-top-level CPT menu items
		if ( is_string( $this->post_type->show_in_menu ) ) {
			$menu_ops['submenu']['parent_slug'] = $this->post_type->show_in_menu;
			$menu_ops['submenu']['menu_title']  = apply_filters( 'bizznis_cpt_archive_settings_label', $this->post_type->labels->name . ' ' . __( 'Archive', 'bizznis' ) );
			$menu_ops['submenu']['menu_position']  = $this->post_type->menu_position;
		}
		$page_ops = array(); # use defaults
		$settings_field = BIZZNIS_CPT_ARCHIVE_SETTINGS_FIELD_PREFIX . $this->post_type->name;
		$default_settings = apply_filters(
			'bizznis_cpt_archive_settings_defaults',
			array(
				'headline'    => '',
				'intro_text'  => '',
				'doctitle'    => '',
				'description' => '',
				'layout'      => '',
				'body_class'  => '',
				'noindex'     => 0,
				'nofollow'    => 0,
				'noarchive'   => 0,
			)
		);
		$this->create( $page_id, $menu_ops, $page_ops, $settings_field, $default_settings );
		add_action( 'bizznis_settings_sanitizer_init', array( $this, 'sanitizer_filters' ) );
	}

	/**
	 * Register each of the settings with a sanitization filter type.
	 *
	 * @since 1.0.0
	 */
	public function sanitizer_filters() {
		bizznis_add_option_filter(
			'no_html',
			$this->settings_field,
			array(
				'headline',
				'doctitle',
				'description',
				'body_class',
			)
		);
		bizznis_add_option_filter(
			'safe_html',
			$this->settings_field,
			array(
				'intro_text',
			)
		);
		bizznis_add_option_filter(
			'one_zero',
			$this->settings_field,
			array(
				'noindex',
				'nofollow',
				'noarchive',
			)
		);
	}

	/**
	 * Register meta boxes on the CPT Archive pages.
	 *
	 * @since 1.0.0
	 */
	public function metaboxes() {
		add_meta_box( 'bizznis-cpt-archives-settings', __( 'Archive Settings', 'bizznis' ), array( $this, 'archive_box' ), $this->pagehook, 'main' );
		add_meta_box( 'bizznis-cpt-archives-layout-settings', __( 'Layout Settings', 'bizznis' ), array( $this, 'layout_box' ), $this->pagehook, 'column2' );
		add_meta_box( 'bizznis-cpt-archives-seo-settings', __( 'SEO Settings', 'bizznis' ), array( $this, 'seo_box' ), $this->pagehook, 'column3' );
		do_action( 'bizznis_cpt_archives_settings_metaboxes', $this->pagehook );
	}

	/**
	 * Callback for Archive Settings meta box.
	 *
	 * @since 1.0.0
	 */
	public function archive_box() {
		?>
		<p><?php printf( __( 'View the <a href="%s">%s archive</a>.', 'bizznis' ), get_post_type_archive_link( $this->post_type->name ), $this->post_type->name ); ?></p>
		<p><label for="<?php echo $this->get_field_id( 'headline' ); ?>"><b><?php _e( 'Archive Headline', 'bizznis' ); ?></b></label></p>
		<p><input class="large-text" type="text" name="<?php echo $this->get_field_name( 'headline' ); ?>" id="<?php echo $this->get_field_id( 'headline' ); ?>" value="<?php echo esc_attr( $this->get_field_value( 'headline' ) ); ?>" /></p>
		<p class="description"><?php _e( 'Leave empty if you do not want to display a headline.', 'bizznis' ); ?></p>
		<p><label for="<?php echo $this->get_field_id( 'intro_text' ); ?>"><b><?php _e( 'Archive Intro Text', 'bizznis' ); ?></b></label></p>
		<p><textarea class="widefat" rows="5" cols="30" name="<?php echo $this->get_field_name( 'intro_text' ); ?>" id="<?php echo $this->get_field_id( 'intro_text' ); ?>"><?php echo esc_textarea( $this->get_field_value( 'intro_text' ) ); ?></textarea></p>
		<p class="description"><?php _e( 'Leave empty if you do not want to display any intro text.', 'bizznis' ); ?></p>
		<?php
	}

	/**
	 * Callback for Layout Settings meta box.
	 *
	 * @since 1.0.0
	 */
	public function layout_box() {
		$layout = $this->get_field_value( 'layout' );
		?>
		<div class="bizznis-layout-selector">
			<p><input type="radio" class="default-layout" name="<?php echo $this->get_field_name( 'layout' ); ?>" id="default-layout" value="" <?php checked( $layout, '' ); ?> /> <label class="default" for="default-layout"><?php printf( __( 'Default Layout set in <a href="%s">Theme Settings</a>', 'bizznis' ), menu_page_url( 'bizznis', 0 ) ); ?></label></p>

			<p><?php bizznis_layout_selector( array( 'name' => $this->get_field_name( 'layout' ), 'selected' => $layout, 'type' => 'site' ) ); ?></p>
		</div>
		<br class="clear" />
		<p><label for="<?php echo $this->get_field_id( 'body_class' ); ?>"><b><?php _e( 'Custom Body Class', 'bizznis' ); ?></b></label></p>
		<p><input class="large-text" type="text" name="<?php echo $this->get_field_name( 'body_class' ); ?>" id="<?php echo $this->get_field_id( 'body_class' ); ?>" value="<?php echo esc_attr( $this->get_field_value( 'body_class' ) ); ?>" /></p>
		<?php
	}
	
	/**
	 * Callback for SEO Settings meta box.
	 *
	 * @since 1.0.0
	 */
	public function seo_box() {
		?>
		<p><label for="<?php echo $this->get_field_id( 'doctitle' ); ?>"><b><?php _e( 'Custom Document Title', 'bizznis' ); ?></b></label></p>
		<p><input class="large-text" type="text" name="<?php echo $this->get_field_name( 'doctitle' ); ?>" id="<?php echo $this->get_field_id( 'doctitle' ); ?>" value="<?php echo esc_attr( $this->get_field_value( 'doctitle' ) ); ?>" /></p>
		<p><label for="<?php echo $this->get_field_id( 'doctitle' ); ?>"><b><?php _e( 'Meta Description', 'bizznis' ); ?></b></label></p>
		<p><input class="large-text" type="text" name="<?php echo $this->get_field_name( 'description' ); ?>" id="<?php echo $this->get_field_id( 'description' ); ?>" value="<?php echo esc_attr( $this->get_field_value( 'description' ) ); ?>" /></p>
		<h4><?php _e( 'Robots Meta Tags:', 'bizznis' ); ?></h4>
		<p>
			<label for="<?php echo $this->get_field_id( 'noindex' ); ?>"><input type="checkbox" name="<?php echo $this->get_field_name( 'noindex' ); ?>" id="<?php echo $this->get_field_id( 'noindex' ); ?>" value="1" <?php checked( $this->get_field_value( 'noindex' ) ); ?> />
			<?php printf( __( 'Apply %s to this archive', 'bizznis' ), bizznis_code( 'noindex' ) ); ?> <a href="<?php printf( __( '%s', 'bizznis' ), 'http://yoast.com/articles/robots-meta-tags/' ); ?>" target="_blank">[?]</a></label><br />

			<label for="<?php echo $this->get_field_id( 'nofollow' ); ?>"><input type="checkbox" name="<?php echo $this->get_field_name( 'nofollow' ); ?>" id="<?php echo $this->get_field_id( 'nofollow' ); ?>" value="1" <?php checked( $this->get_field_value( 'nofollow' ) ); ?> />
			<?php printf( __( 'Apply %s to this archive', 'bizznis' ), bizznis_code( 'nofollow' ) ); ?> <a href="<?php printf( __( '%s', 'bizznis' ), 'http://yoast.com/articles/robots-meta-tags/' ); ?>" target="_blank">[?]</a></label><br />

			<label for="<?php echo $this->get_field_id( 'noarchive' ); ?>"><input type="checkbox" name="<?php echo $this->get_field_name( 'noarchive' ); ?>" id="<?php echo $this->get_field_id( 'noarchive' ); ?>" value="1" <?php checked( $this->get_field_value( 'noarchive' ) ); ?> />
			<?php printf( __( 'Apply %s to this archive', 'bizznis' ), bizznis_code( 'noarchive' ) ); ?> <a href="<?php printf( __( '%s', 'bizznis' ), 'http://yoast.com/articles/robots-meta-tags/' ); ?>" target="_blank">[?]</a></label>
		</p>
		<?php
	}

	/**
	 * Add contextual help content for the archive settings page.
	 *
	 * @since 1.0.0
	 */
	public function help() {
		$screen = get_current_screen();
		$archive_help =
			'<h3>' . __( 'Archive Settings', 'bizznis' ) . '</h3>' .
			'<p>' . __( 'The Archive Headline sets the title seen on the archive page', 'bizznis' ) . '</p>' .
			'<p>' . __( 'The Archive Intro Text sets the text before the archive entries to introduce the content to the viewer.', 'bizznis' ) . '</p>';
		$screen->add_help_tab(
			array(
				'id'      => $this->pagehook . '-archive',
				'title'   => __( 'Archive Settings', 'bizznis' ),
				'content' => $archive_help,
			)
		);
		$seo_help =
			'<h3>' . __( 'SEO Settings', 'bizznis' ) . '</h3>' .
			'<p>' . __( 'The Custom Document Title sets the page title as seen in browsers and search engines. ', 'bizznis' ) . '</p>' .
			'<p>' . __( 'The Meta description fills in the meta tags for the archive page. The Meta description is the short text blurb that appear in search engine results.', 'bizznis' ) . '</p>' .
			'<p>' . __( 'The Robots Meta Tags tell search engines how to handle the archive page. Noindex means not to index the page at all, and it will not appear in search results. Nofollow means do not follow any links from this page and noarchive tells them not to make an archive copy of the page.', 'bizznis' ) . '</p>';
		$screen->add_help_tab(
			array(
				'id'      => $this->pagehook . '-seo',
				'title'   => __( 'SEO Settings', 'bizznis' ),
				'content' => $seo_help,
			)
		);
		$layout_help =
			'<h3>' . __( 'Layout Settings', 'bizznis' ) . '</h3>' .
			'<p>'  . __( 'This lets you select the layout for the archive page. On most of the child themes you\'ll see these options:' , 'bizznis' ) . '</p>' .
			'<ul>' .
				'<li>' . __( 'Content Sidebar' , 'bizznis' ) . '</li>' .
				'<li>' . __( 'Sidebar Content' , 'bizznis' ) . '</li>' .
				'<li>' . __( 'Sidebar Content Sidebar' , 'bizznis' ) . '</li>' .
				'<li>' . __( 'Content Sidebar Sidebar' , 'bizznis' ) . '</li>' .
				'<li>' . __( 'Sidebar Sidebar Content' , 'bizznis' ) . '</li>' .
				'<li>' . __( 'Full Width Content' , 'bizznis' ) . '</li>' .
			'</ul>' .
			'<p>'  . __( 'These options can be extended or limited by the child theme.' , 'bizznis' ) . '</p>' .
			'<p>'  . __( 'The Custom Body Class adds a class to the body tag in the HTML to allow CSS modification exclusively for this post type\'s archive page.' , 'bizznis' ) . '</p>';
		$screen->add_help_tab(
			array(
				'id'      => $this->pagehook . '-layout',
				'title'   => __( 'Layout Settings', 'bizznis' ),
				'content' => $layout_help,
			)
		);
	}
}
