<?php 
/*
	WARNING! DO NOT EDIT THIS FILE!
	This file is part of the core Bizznis parent theme. 
	Please do all modifications in the form of a child theme.
*/

/**
 * Display Warning that Bizznis should always be used with a child theme.
 *
 * @since 1.4.0
 */
add_action( 'admin_notices', 'bizznis_use_child_theme_notice' );
function bizznis_use_child_theme_notice() {

	if ( is_child_theme() ) {
		return;
	}

	$allowed_html = array(
		'a' => array(
			'href' => array(),
		),
	);

	echo '<div class="error"><p><strong>';
	esc_html_e( 'Please Activate a Bizznis Child Theme:', 'bizznis' );
	echo '</strong> ';
	esc_html_e( 'We\'ve noticed you are using the Bizznis parent theme alone. We strongly recommend you run a Bizznis child theme with it (we even have a free theme you can use). ', 'bizznis' );
	printf(
		wp_kses( __( 'For more information, see our article at <a href="%1$s$">%1$s</a>', 'bizznis' ), $allowed_html ),
		esc_url( __( 'https://bizzthemes.com/bizznis-always-use-child-theme/', 'bizznis' ) )
	);
	echo '</p></div>';
}
