<?php
/*
	WARNING! DO NOT EDIT THIS FILE!
	This file is part of the core Bizznis parent theme. 
	Please do all modifications in the form of a child theme.
*/

/**
 * Deprecated. Output the title, wrapped in title tags.
 *
 * @since 1.0.0
 * @deprecated 1.3.0
 */
add_action( 'bizznis_init', 'deprecated_constants' );
function deprecated_constants() {
	define( 'BIZZNIS_ADMIN_IMAGES_DIR', 	BIZZNIS_ASSETS_IMAGES_DIR );
	define( 'BIZZNIS_ADMIN_CSS_DIR', 		BIZZNIS_ASSETS_CSS_DIR );
	define( 'BIZZNIS_ADMIN_JS_DIR', 		BIZZNIS_ASSETS_JS_DIR );
	define( 'BIZZNIS_ADMIN_IMAGES_URL', 	BIZZNIS_ASSETS_IMAGES_URL );
	define( 'BIZZNIS_ADMIN_CSS_URL', 		BIZZNIS_ASSETS_CSS_URL );
	define( 'BIZZNIS_ADMIN_JS_URL', 		BIZZNIS_ASSETS_JS_URL );
}

/**
 * Deprecated. Echo custom rel="author" link tag.
 *
 * If the appropriate information has been entered, either for the homepage author, or for an individual post/page
 * author, echo a custom rel="author" link.
 *
 * @since 1.0.0
 * @deprecated 1.2.2
 */
function bizznis_rel_author() {
	_deprecated_function( __FUNCTION__, '1.2.2' );
	$post = get_post();
	# If the appropriate information has been entered for an individual post/page
	if ( is_singular() && post_type_supports( $post->post_type, 'bizznis-rel-author' ) && isset( $post->post_author ) && $gplus_url = get_user_option( 'googleplus', $post->post_author ) ) {
		printf( '<link rel="author" href="%s" />' . "\n", esc_url( $gplus_url ) );
		return;
	}
	# If the appropriate information has been entered for an individual author archive
	if ( is_author() && get_query_var( 'author' ) && $gplus_url = get_user_option( 'googleplus', get_query_var( 'author' ) ) ) {
		printf( '<link rel="author" href="%s" />' . "\n", esc_url( $gplus_url ) );
		return;
	}
}

/**
 * Deprecated. Push individual setting (or group of setting) into an options db entry stored as an array.
 *
 * @since 1.0.0
 * @deprecated 1.1.0
 */
function _bizznis_update_settings( $new, $setting = null ) {
	_deprecated_function( __FUNCTION__, '1.1.0', "bizznis_update_setting" );
	bizznis_update_settings( $new, $setting );
}

/**
 * Deprecated. Ouput site title.
 *
 * @since 1.0.0
 * @deprecated 1.1.0
 */
function bizznis_seo_site_title() {
	_deprecated_function( __FUNCTION__, '1.1.0', "bizznis_update_setting" );
	bizznis_site_title();
}

/**
 * Deprecated. Ouput site tagline.
 *
 * @since 1.0.0
 * @deprecated 1.1.0
 */
function bizznis_seo_site_description() {
	_deprecated_function( __FUNCTION__, '1.1.0', "bizznis_update_setting" );
	bizznis_site_description();
}

/**
 * Deprecated. Output the title, wrapped in title tags.
 *
 * @since 1.0.0
 * @deprecated 1.1.4
 */
if ( ! function_exists( '_wp_render_title_tag' ) ) :
	add_action( 'wp_head', 'bizznis_do_title', 1 );
	function bizznis_do_title() {
		_deprecated_function( __FUNCTION__, '1.1.4', "_wp_render_title_tag" );
		?><title><?php wp_title( '' ); ?></title><?php
	}
endif;

/**
 * Deprecated. Output the title, wrapped in title tags.
 *
 * @since 1.0.0
 * @deprecated 1.3.1
 */
add_action( 'wp_head', 'deprecated_footer_creds_text_filter' );
function deprecated_footer_creds_text_filter() {
	if ( has_filter( 'bizznis_footer_creds_text', 'company_add_back_to_top' ) ) {
		remove_action( 'bizznis_footer_inner', 'bizznis_footer_credits' );
		add_action( 'bizznis_footer_inner', 'do_bizznis_footer_creds_text' );
		add_filter( 'bizznis_footer_creds_text', 'do_shortcode', 20 );
	}
}

function do_bizznis_footer_creds_text() {
	# Build the text strings. Includes shortcodes
	$backtotop_text = '[footer_backtotop]';
	$creds_text     = sprintf( '<p>[footer_copyright before="%s "] &#x000B7; [footer_childtheme_link before="" after=""] [footer_bizzthemes_link url="http://www.bizzthemes.com/" before="%s "] &#x000B7; [footer_wordpress_link] &#x000B7; [footer_loginout]</p>', __( 'Copyright', 'bizznis' ), __( 'by', 'bizznis' ) );
	# Filter the text strings
	$creds_text     = apply_filters( 'bizznis_footer_creds_text', $creds_text, $backtotop_text );
	# Build output
	$output = sprintf( '<div %s>', bizznis_attr( 'footer-creds' ) );
	$output .= bizznis_wrapper( 'footer-creds-wrapper', 'open', false ); #wrapper
	$output .= $creds_text;
	$output .= bizznis_wrapper( 'footer-creds-wrapper', 'close', false ); #wrapper
	$output .= '</div>';
	echo $output;
}
